# Generated by Django 2.1.2 on 2018-12-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingstore', '0002_brand_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='city',
        ),
    ]
