# Generated by Django 2.1.2 on 2018-12-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billingstore', '0003_remove_brand_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='billingstore.Company')),
            ],
        ),
    ]
