# Generated by Django 2.1.2 on 2018-11-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingstore', '0002_brand_cities'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='billingstore.Company'),
        ),
    ]
