# Generated by Django 2.1.2 on 2018-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit', models.CharField(choices=[('kg', 'Kilogramo'), ('lb', 'Libra')], default='kg', max_length=50)),
                ('equivalence_unit', models.CharField(choices=[('kg', 'Kilogramo'), ('lb', 'Libra')], default='kg', max_length=50)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kg', 'Kilogramo'), ('lb', 'Libra')], default='kg', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equivalence',
            name='unit',
            field=models.ManyToManyField(to='products.Unit'),
        ),
    ]
