# Generated by Django 2.1.2 on 2018-11-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billingstore', '0001_initial'),
        ('products', '0004_auto_20181128_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InactiveProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_at', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('base_unit', models.CharField(choices=[('kg', 'Kilogramo'), ('lb', 'Libra')], default='kg', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pvp_brand', models.DecimalField(decimal_places=10, max_digits=20)),
                ('pvp', models.DecimalField(decimal_places=10, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billingstore.Brand')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='inactiveproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Product'),
        ),
        migrations.AddField(
            model_name='alternatecode',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
